### ISSUE TITLE
Error in "enumerate(train_loader)"

### ISSUE THREAD

**Issue by narminGhaffari** [Dipeshtamboli/Image-Classification-and-Localization-using-Multiple-Instance-Learning#3]
In train_n_test script, When I want to enumerate(trainLoader), I got this error:  

`Can't pickle <class 'patch_data.PatchMethod'>: it's not the same object as patch_data.PatchMethod
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\anaconda3\envs\torchEnv\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\User\anaconda3\envs\torchEnv\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\anaconda3\envs\torchEnv\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\User\anaconda3\envs\torchEnv\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\anaconda3\envs\torchEnv\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\User\anaconda3\envs\torchEnv\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\anaconda3\envs\torchEnv\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\User\anaconda3\envs\torchEnv\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
`

What can be the reason for that?
Thank you!

**Comment by Dipeshtamboli** [comment]
I guess the data you have is not in the same folder structure, just as mentioned in the readme.md file. Because of that, your data loader cannot load the data properly, thus causing this error. Can you please check if your train_loader is properly working?
